### PR TITLE
use virtualbox 5.2 api to get vbox

### LINKED ISSUE #11: Not detecting VMs on VirtualBox 5.2
Just upgraded to 5.2 and typing `vm` doesn't seem to detect any of my VMs. Anyone else having this issue?

Error in debug log:
```
[2017-10-31 10:16:53][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "vm_list.py", line 11, in <module>
    vbox = mgr.vbox
AttributeError: 'VirtualBoxManager' object has no attribute 'vbox'
```

Not sure if this is an import error in python?

### PR DESCRIPTION
**Pull request by kevinkwl**
should fix #11 .
In 5.1 api, they have
```python        
        try:
              self.vbox = self.platform.getVirtualBox()
```
in the init of VirtualBoxManager, but in 5.2, the `self` is missing, only vbox, I don't know why...

### CODE REVIEW

**Comment by fniephaus** [comment]
Thanks! Why the additional try-except block? If it's just re-raising the exception, it can be left out completely, right?

**Comment by kevinkwl** [comment]
I wanted to give some additional error messages but left it blank... Maybe it does not need that, I'll remove the try-except block.

**Comment by xilopaint** [comment]
Still not working for me.

**Comment by fniephaus** [comment]
@xilopaint what error are you seeing? And could you please open a new issue?

**Comment by xilopaint** [comment]
Sure, I can open a new issue, but before that I want to ensure I'm not missing anything obvious as I have installed this workflow some days ago and never could get it to work.

No errors are displayed on console:

```Starting debug for 'VM Control'

[2017-11-22 14:15:29][input.scriptfilter] Queuing argument ''
[2017-11-22 14:15:29][input.scriptfilter] Script with argument '(null)' finished
[2017-11-22 14:15:29][STDERR: input.scriptfilter] 14:15:29 workflow.py:2247 DEBUG    ---------- VM Control (1.7.0) ----------
14:15:29 workflow.py:1657 DEBUG    reading settings from /Users/xxxx/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.vmcontrol/settings.json
14:15:29 workflow.py:2440 DEBUG    set last run version: 1.7.0
14:15:29 workflow.py:2289 DEBUG    ---------- finished in 0.107s ----------
[2017-11-22 14:15:29][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items />

**Comment by fniephaus** [comment]
Are you using VirtualBox? If yes, which version?

**Pull request merged**
